services:
  backend:
    build: ./backend
    image: scoliotect-mini-backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    image: scoliotect-mini-frontend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5174:80"
    depends_on:
      - backend
